sudo: required

language: generic

env:
  REPO: docksal/unison

services:
  - docker

install:
#

before_script:
#

script:
  - docker build . -t ${REPO}:latest

after_success: |
  docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
  docker push ${REPO}

after_failure:
  - echo "Failed"
