sudo: required

language: generic

env:
  REPO: docksal/unison
  IMAGE: ${REPO}:dev
  DOCKSAL_VERSION: develop

services:
  - docker

install:
#

before_script:
#

script:
  - TAG="latest"
  - docker build ${REPO}:${TAG}

after_success: |
  echo "After success begin. PR: $TRAVIS_PULL_REQUEST"
  # if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
  #   # develop => edge
  #   [[ "${TRAVIS_BRANCH}" == "develop" ]] && TAG="edge"
  #   # master => latest
  #   [[ "${TRAVIS_BRANCH}" == "master" ]] && TAG="latest"
  #   # tags/v1.2.0 => 1.2
  #   [[ "${TRAVIS_TAG}" != "" ]] && TAG="${TRAVIS_TAG:1:3}"
    TAG="latest"
    echo "TAG: $TAG"

    if [[ "$TAG" != "" ]]; then
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      docker tag ${IMAGE} ${REPO}:${TAG}
      docker push ${REPO}:${TAG}
    fi
  # fi

after_failure:
  - echo "Failed"
